From: ubuntu:12.04
Bootstrap: docker

%help
genometools 1.5.9

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/genometools-1.5.9:$PATH
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget git build-essential libcairo2-dev libpango1.0-dev unzip -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  cd /usr/local/src && wget http://genometools.org/pub/genometools-1.5.9.tar.gz -O gt.tar.gz && tar xf gt.tar.gz && rm gt.tar.gz && cd genometools-1.5.9 &&  make -j 8 64bit=yes cairo=no install
  mkdir /scratch
