From: ubuntu:artful
Bootstrap: docker

%help
bowtie 2.3.4.1

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/bowtie2-2.3.4.1-linux-x86_64:$PATH
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget git build-essential unzip -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  cd /usr/local/src && wget https://datapacket.dl.sourceforge.net/project/bowtie-bio/bowtie2/2.3.4.1/bowtie2-2.3.4.1-linux-x86_64.zip -O bowtie2.zip && unzip bowtie2.zip && rm bowtie2.zip
  mkdir /scratch
