From: ubuntu:artful
Bootstrap: docker

%help
trimgalore 0.4.5

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/FastQC:$PATH
  PATH=/usr/local/src/TrimGalore-0.4.5:$PATH
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget python python-pip build-essential unzip openjdk-9-jre -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  pip install cutadapt
  cd /usr/local/src && wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip -O fastqc.zip && unzip fastqc.zip && rm fastqc.zip && chmod +X FastQC/fastqc && chmod 755 FastQC/fastqc
  cd /usr/local/src && wget https://github.com/FelixKrueger/TrimGalore/archive/0.4.5.zip -O trimgalore.zip && unzip trimgalore.zip && rm trimgalore.zip 
  mkdir /scratch
