From: ubuntu:artful
Bootstrap: docker

%help
RSEM 1.3.0

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/bowtie2-2.3.4.1-linux-x86_64:$PATH
  PATH=/usr/local/src/RSEM-1.3.0:$PATH
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget unzip build-essential python zlib1g-dev -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  cd /usr/local/src && wget https://datapacket.dl.sourceforge.net/project/bowtie-bio/bowtie2/2.3.4.1/bowtie2-2.3.4.1-linux-x86_64.zip -O bowtie2.zip && unzip bowtie2.zip && rm bowtie2.zip
  cd /usr/local/src && wget https://github.com/deweylab/RSEM/archive/v1.3.0.tar.gz -O rsem.tar.gz && tar xf rsem.tar.gz && rm rsem.tar.gz && cd RSEM-1.3.0 && make -j 8
  mkdir /scratch
