From: ubuntu:artful
Bootstrap: docker

%help
blast+ 2.7.1

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/ncbi-blast-2.7.1+/bin:$PATH
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget git build-essential liblist-moreutils-perl -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  cd /usr/local/src && wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz -O blast.tar.gz && tar xf blast.tar.gz && rm blast.tar.gz
  mkdir /scratch
