From: ubuntu:artful
Bootstrap: docker

%help
busco 3.0.2

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  PATH=/usr/local/src/busco/scripts:$PATH
  PATH=/usr/local/src/augustus/bin:$PATH
  PATH=/usr/local/src/augustus/scripts:$PATH
  AUGUSTUS_CONFIG_PATH=/usr/local/src/augustus/config/
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install python3 git wget build-essential unzip libboost-all-dev libsuitesparse-dev liblpsolve55-dev libgsl-dev libgsl23 gsl-bin hmmer ncbi-blast+ libboost-iostreams-dev bamtools libbamtools-dev lib32z1-dev mafft autoconf flex bison libtool raxml -y && rm -rf /var/lib/apt/lists/*
  mkdir -p /usr/local/src
  cd /usr/local/src && git clone https://gitlab.com/ezlab/busco.git && cd busco && python3 setup.py install --user 
  cd /usr/local/src && wget http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.1.tar.gz -O augustus.tar.gz && tar xf augustus.tar.gz && rm augustus.tar.gz && cd augustus && make -j 8 && make -j 8 install
  mkdir -p /scratch
