From: ubuntu:artful
Bootstrap: docker

%help
nanoplot 1.13.0

%labels
  Maintainer Andrei Rozanski
  Version v1.0

%environment
  export LC_ALL=C

%post
  apt-get update && apt-get dist-upgrade -y && apt-get install wget git build-essential unzip python3 python3-pip -y && rm -rf /var/lib/apt/lists/*
  pip3 install NanoPlot matplotlib
  mkdir /scratch
